name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: docker login
      run: docker login -u jeyrce -p ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag image-build-test:$(date +%s)
