name: Release Publish

on:
  push:
    tags: ['v*']
    
env:
  VERSION: ${{ github.ref_name }}
  AUTH: ${{ secrets.DOCKER_HUB_TOKEN }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: docker login        
      run: docker login -u jeyrce -p "$AUTH"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jeyrce/image-build-test:"$VERSION"
    - name: Image push
      run: docker push jeyrce/image-build-test:"$VERSION"
